### ISSUE TITLE
The container keeps running

### ISSUE THREAD

**Issue by muhammadfaizan** [recurship/docker-khi-workshop-01#4]
I just completed exercisse-6 and the container is stopped, but the port is still accessible from `8080`,
infact in later exercise i was unable to bind any container port to `8080` because it was already utilized
 
![image](https://user-images.githubusercontent.com/5428176/34643829-194d0b00-f34d-11e7-8ac5-10fe5ff0b464.png)

as you can see there is no container bind to port `8080` but yet the website is still accessible.

![image](https://user-images.githubusercontent.com/5428176/34643860-80a94a34-f34d-11e7-82ad-517cd99c2e40.png)
Can you please help me understand what can be possibly wrong here !?

**Comment by aitchkhan** [comment]
I don't see any container attached to port 8080 in your `ls` command. 
Can you try `netstat -nlp | grep 8080` and paste the output here?

**Comment by mashhoodr** [comment]
Try rebooting your machine, could be the port didnt deallocate properly.

**Comment by muhammadfaizan** [comment]
but that should not be the issues..!

**Comment by muhammadfaizan** [comment]
@aitchkhan yes thats what the issue was, that the port seemed to remain bind, also container seemed to remain binded, rebooting helped, but that should not happen, should i report this issue to docker?

**Comment by mashhoodr** [comment]
Yeah you can report it, but it could also be some Linux quirk. You will need to be able to replicate this repeatedly.

**Comment by aitchkhan** [comment]
@faizan not unless you are able to reproduce it repeatedly like @mashood
said.

**Comment by muhammadfaizan** [comment]
I would try to reproduce it.
