### ISSUE TITLE
Excercise 4 Vim Error

### ISSUE THREAD

**Issue by nasirhm** [recurship/docker-khi-workshop-01#8]
Vim is not installed by default in the Alpine Linux.

**Comment by mohuk** [comment]
Correct. I tried `node:8.7.0-alpine` and it did not have `vim` installed but it does have `vi` which is an older version of `vim`.

[What is the difference between vi and vim](https://askubuntu.com/questions/418396/what-is-the-difference-between-vi-and-vim)

**Comment by mashhoodr** [comment]
@mohuk do we need to update anything in the exercises?

**Comment by nasirhm** [comment]
vi command is also not found. @mashhoodr @mohuk

**Comment by nasirhm** [comment]
![sss](https://user-images.githubusercontent.com/35005234/35233090-01d70eec-ff52-11e7-8a46-1c292716c1dc.PNG)

**Comment by nasirhm** [comment]
The Correction is that you have to add a line before vi 
First download vim by using apt-get install vim
and use vim to edit.

**Comment by mohuk** [comment]
In the image above you are running `httpd` instead of `httpd:alpine`. Please try this with `httpd:alpine`. 

I just tried it and it works.

Also, `apt-get` doesn't work on `alpine`.

**Comment by mashhoodr** [comment]
@nasirhm please use httpd:alpine as per the instructions in readme. That should fix the issue

**Comment by nasirhm** [comment]
Ah Sorry my Mistake
